# 各种无关性描述文字
# 启动器上的游戏名字
GameName: '资本家模拟器（2021国庆测试版）'
Text:
  Description1: "新风暴：自从极东之地的金融波动之后，震坦和四岛社会已经运转到了极限，人们纷纷追忆起三年前萨布林娜小姐在全国广播里的讲话，高声唱起图书馆之歌来，似乎是可以念一首《海燕》了。" 
  Description2: "大洪水：资本家对自然资源的需求无穷无尽，三罗和震坦首先出现了能源危机，矛盾转移掩盖不了两极渐渐融化的冰川，洪水的时代要到来了。但东国的废水催生了一只庞大的海洋生物无人看见它的容貌，能看见它容貌的人都疯了。"
  Description3: "黑太阳：新大陆的大火山爆发了，联邦国在一周之间分崩离析漫天尘埃遮蔽了阳光。阳之力的缺失导致灵异复苏，来自地狱的导师回到了他奋斗的世界——’此去阎台招旧部，十万旌旗斩阎罗。"
# 窗体上的描述性文字
Window:
  Button_Yes: "是"
  Button_No: "否"
  Button_Cancel: "取消"
# 类似背景设定之类的可以放到这里
# 如果有剧本等请另外建立 YAML 配置文件
JvBen:
  JvBen1: '新风暴：自从极东之地的金融波动之后，震坦和四岛社会已
           经运转到了极限，人们纷纷追忆起三年前萨布林娜小姐在全
           国广播里的讲话，高声唱起图书馆之歌来，似乎是可以念一
           首《海燕》了。'

  JvBen2: '大洪水：资本家对自然资源的需求无穷无尽，三罗和震坦
           首先出现了能源危机，矛盾转移掩盖不了两极渐渐融化的冰
           川，洪水的时代要到来了。但东国的废水催生了一只庞大的
           海洋生物无人看见它的容貌，能看见它容貌的人都疯了。'

  JvBen3: '黑太阳：新大陆的大火山爆发了，联邦国在一周之间分崩离
           析。漫天的尘埃遮蔽了阳光，阳光的缺失导致灵异复苏，来
           自地狱的革命党回到了他忠诚的世界—’此去阎台招旧部，十
           万旌旗斩阎罗。'

# 游戏启动器上的身份介绍字符串
jieshao_QuanShi : '拳师：分裂社会的恐怖分子，可以使用技能获得“CIA补贴“经常刺杀男性网约车司机,但该职业容易入狱。'
jieshao_HaiGui: '海龟贵物：海外归来的留学生，但与其它人不同的是，这批‘海龟’已经被西方错误价值观洗脑了，他们大肆反对祖国，散播不良弱智言论。'
jieshao_TianLongRen: '天龙人：帝都的高等居民，由于比其他省份人民的生活水平高了好几倍，所以部分人根本看不起其他地区的群众。可以使用技能“正黄旗贵族”额外获得大量资源点'
jieshao_WangYiYun: '网抑云：在网络平台上传播负能量的生物，可以使用技能”口红割腕“经常在半夜听歌时狂暴流泪，疑似压力过大导致的压力马斯内'
jieshao_ZuoJia: '网文作家：除了跨性别繁殖之外，几乎什么都懂一点，可以使用技能‘芝加哥打字机’，但部分写手会要求别人删文——“你能删一个小时吗”'
jieshao_ZuoTiJia: '做题家（卷王）：从小卷到大的鬼才，部分人的目标是去拱了城里的白菜。但由于经常高强度996和偶尔007，卷怪的身体强度一日不如一日。'
jieshao_ZhangXianZhong: '张献忠：我决定那个从今天开始杀人，一天杀一个，直到那个过年。杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀杀。'
jieshao_HanHuang: '大民族主义：我们震坦真是太厉害啦！永恒之城其实是震坦人建造的！西方金字塔是波拿巴超人一人抗五万吨石块一个月造起来欺骗国民的！天子守国门！君王死社稷！嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷嗷！！！'
jieshao_ZuoRen: '左翼：康米正统！猫猫正统！先知正统！慈父正统！导师正统！社民正统！（网络角斗场）。我超你们都是啥寄吧玩意啊————革你左籍！'
jieshao_ChengXvYuan: '程序员：程序和我，有一个能跑就行。屎山挖粪，应该去买一瓶护发水来着————'
jieshao_LSP: '老司机：你只管开车，办法由老爹来想。'
jieshao_TuMuGou: '土木狗：别水群啦，包工头喊你吃饭了!'
jieshao_GongZhi: '公知：灯塔全民免费医保！在微信军事基地部署有1000艘医疗船！高速公路不收费，人人买得起帝国大厦，开得起核动力飞车！注重“快乐教育”，孩子们课业压力为负五十万！公司关怀员工，给他们每个人500%股份！'
jieshao_TangPing: '躺平人：谢邀，天桥下睡得很舒服，每天可以免费喝水吃小绿藻我超！我生活的无忧无虑！'
jieshao_SheChu: '社畜：心口有点疼，现在是几点？我去公司天台晾个衣服——哎？老板好！我一定会在今年让您开上迈巴赫的！'
jieshao_2CiYuan: '二刺螈：（（（（（（（（（呐）））））））））（（（（（（（（（呐）））））））））（（（（（（（（（呐）））））））））'
jieshao_XPi: 'X批：我是充648好呢，还是充648？'
jieshao_DianJingFen: '电竞粉：部分人会打泰拳，部分人会御剑，还有部分人仰卧起坐的能力很强喜欢睡在棺材里，时不时出来看一眼。'

# 游戏启动器上的身份名称
SF:
  name1 : '拳师'
  name2 : '天龙人'
  name3 : '海龟贵物'
  name4 : '网抑云'
  name5 : '作家塔塔开'
  name6 : '做题家'
  name7 : '张献忠'
  name8 : '汉皇'
  name9 : '左人'
  name10: '码农'
  name11: '老司机'
  name12: '土木狗'
  name13: '公知'
  name14: '下水道'
  name15: '社畜'
  name16: '萌萌人'
  name17: 'X批'
  name18: '电竞粉'
