# 各种无关性描述文字
# 类似背景设定之类的可以放到这里
# 如果有剧本等请另外建立 YAML 配置文件
Text:
  Description1: "新风暴：自从极东之地的金融波动之后，震坦和四岛社会已经运转到了极限，人们纷纷追忆起三年前萨布林娜小姐在全国广播里的讲话，高声唱起图书馆之歌来，似乎是可以念一首《海燕》了。" 
  Description2: "大洪水：资本家对自然资源的需求无穷无尽，三罗和震坦首先出现了能源危机，矛盾转移掩盖不了两极渐渐融化的冰川，洪水的时代要到来了。但东国的废水催生了一只庞大的海洋生物无人看见它的容貌，能看见它容貌的人都疯了。"
  Description3: "黑太阳：新大陆的大火山爆发了，联邦国在一周之间分崩离析漫天尘埃遮蔽了阳光。阳之力的缺失导致灵异复苏，来自地狱的导师回到了他奋斗的世界——’此去阎台招旧部，十万旌旗斩阎罗。"
# 窗体上的描述性文字
Window:
  Button_Yes: "是"
  Button_No: "否"
  Button_Cancel: "取消"
